site_name: Lectures on the Fourier Transform and Its Applications
theme: readthedocs

nav:
  - Home: index.md
  - Chapter 01 Notes : ch01notes.md
  - Appendix B : appendix-b.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML
 
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
repo_name: Github
repo_url: https://github.com/eroicaleo/fourier-transform/
edit_uri: 'blob/main/docs/'
